palette = "catppuccin_mocha"

format = """
$directory[](fg:peach bg:surface1)\
$git_branch\
$git_status[](fg:surface1 bg:none)\
$fill\
$cmd_duration\
$php\
$time\
$line_break\
$status\
$git_state\
[ ](bold fg:peach)\
"""

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bg:peach bold fg:mantle"
format = "[   $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
truncation_length = 15
symbol = ""
style = "bg:surface1 bold fg:text"
format = "[ $symbol $branch ]($style)"

# nf-oct family fonts
[git_status]
conflicted = ""
ahead = ""
behind = ""
diverged = ""
deleted = ""
style = "bg:surface1 bold fg:text"
format = "([$all_status$ahead_behind ]($style))"

[fill]
symbol = " "

[cmd_duration]
min_time = 1000
style = "bold fg:flamingo"
format = "[$duration ]($style)"

[php]
symbol = ""
style = "bold fg:lavender"
format = "[ $symbol $version ]($style)"

[time]
disabled = false
style = "bold fg:text"
format = "[ $time ]($style)"
time_format = "%R"

[line_break]
disabled = false

[status]
disabled = false
symbol = " "
format = "[$symbol$status ]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"

